"""
English -> German translation using Helsinki-NLP/opus-mt-en-de (MarianMT).

Translates all rows with language == 'en' in the unified DataFrame,
replacing the `text` column with the German translation and updating
`language` from 'en' to 'de' only when translation succeeds.

Translated English data is treated as silver data for auxiliary training
in a multilingual netiquette classification pipeline. Final evaluation
is performed exclusively on real German (gold) data.

A disk cache (data/cache/translations_en_de.parquet) stores completed
translations keyed by MD5 hash of the source text, so repeated runs
skip already-translated rows.

Usage
-----
    from src.preprocessing.translate import EnglishToGermanTranslator

    translator = EnglishToGermanTranslator(
        cache_path="data/cache/translations_en_de.parquet"
    )
    df_de = translator.translate(df)
"""

import hashlib
import logging
import re
from pathlib import Path
from typing import Dict, List, Optional, Union

import pandas as pd
from tqdm import tqdm

logger = logging.getLogger(__name__)

MODEL_NAME = "Helsinki-NLP/opus-mt-en-de"

_REQUIRED_COLUMNS = {"text", "language"}
_CACHE_COLUMNS = {"hash", "translated"}


class EnglishToGermanTranslator:
    """
    Translate English rows in a DataFrame to German (silver data).

    Only rows where ``language == 'en'`` are eligible for translation.
    All other rows are returned unchanged. The original DataFrame is never mutated.

    Output columns added/modified:
        - ``text``:
            Replaced with German translation on success
        - ``language``:
            Updated to 'de' on success only
        - ``text_original``:
            Original English text for all English rows
        - ``is_translated``:
            True if translation succeeded, False otherwise
        - ``translation_status``:
            One of: 'not_applicable', 'success', 'empty', 'failed'

    Args:
        cache_path:
            Path to a parquet file used to persist translations across runs.
            Pass None to disable caching.
        batch_size:
            Number of texts per translation batch. Larger batches are faster
            on GPU; reduce if you hit OOM errors.
        max_length:
            Maximum input token length for tokenization.
        generation_max_new_tokens:
            Maximum number of output tokens generated by the model.
        device:
            'cpu', 'cuda', or 'mps'. Defaults to auto-detect.
    """

    def __init__(
        self,
        cache_path: Optional[Union[str, Path]] = None,
        batch_size: int = 32,
        max_length: int = 512,
        generation_max_new_tokens: int = 128,
        device: Optional[str] = None,
    ) -> None:
        self.batch_size = batch_size
        self.max_length = max_length
        self.generation_max_new_tokens = generation_max_new_tokens
        self.cache_path = Path(cache_path) if cache_path else None
        self.device = device or self._default_device()

        self._cache: Dict[str, str] = {}
        self._model = None
        self._tokenizer = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def translate(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Return a copy of *df* with eligible English rows translated to German.

        Successful rows:
            - ``text`` becomes German translation
            - ``language`` becomes ``de``
            - ``text_original`` stores the original English text
            - ``is_translated`` becomes True
            - ``translation_status`` becomes ``success``

        Empty English rows:
            - remain unchanged
            - ``translation_status`` becomes ``empty``

        Failed English rows:
            - remain unchanged
            - ``translation_status`` becomes ``failed``

        Non-English rows:
            - remain unchanged
            - ``translation_status`` becomes ``not_applicable``

        Raises:
            ValueError: If required columns are missing.
        """
        self._validate_columns(df)

        df_out = df.copy()
        df_out["text_original"] = None
        df_out["is_translated"] = False
        df_out["translation_status"] = "not_applicable"

        english_mask = df_out["language"] == "en"
        n_english = int(english_mask.sum())

        if n_english == 0:
            logger.info("No English rows found - nothing to translate.")
            return df_out

        english_indices = df_out.index[english_mask]
        raw_texts: List[str] = (
            df_out.loc[english_indices, "text"].fillna("").astype(str).tolist()
        )

        # Preserve the original English text for all English rows
        df_out.loc[english_indices, "text_original"] = raw_texts

        # Cleaned texts are used for hashing and as translation input.
        # raw_texts are preserved in text_original and never used as model input.
        cleaned_texts: List[str] = [_clean_text(t) for t in raw_texts]

        empty_positions = [i for i, text in enumerate(cleaned_texts) if not text.strip()]
        non_empty_positions = [i for i, text in enumerate(cleaned_texts) if text.strip()]

        if empty_positions:
            empty_indices = [english_indices[i] for i in empty_positions]
            df_out.loc[empty_indices, "translation_status"] = "empty"

        if not non_empty_positions:
            logger.info("All English rows are empty or whitespace-only - nothing to translate.")
            return df_out

        self._load_cache()
        self._load_model()

        # Hash the cleaned text — consistent across runs as long as cleaning is deterministic
        hashes = [_md5(text) for text in cleaned_texts]

        miss_positions = [
            pos for pos in non_empty_positions if hashes[pos] not in self._cache
        ]

        n_hits = len(non_empty_positions) - len(miss_positions)
        n_empty = len(empty_positions)

        logger.info(
            "Translating %s English rows -> German (model: %s)",
            f"{n_english:,}",
            MODEL_NAME,
        )
        logger.info(
            "Cache hits: %s | To translate: %s | Empty/skipped: %s",
            f"{n_hits:,}",
            f"{len(miss_positions):,}",
            f"{n_empty:,}",
        )

        if miss_positions:
            texts_to_translate = [cleaned_texts[pos] for pos in miss_positions]
            translations = self._translate_in_batches(texts_to_translate)

            for pos, translation in zip(miss_positions, translations):
                if translation is not None:
                    self._cache[hashes[pos]] = translation

            self._save_cache()

        n_success = 0
        n_failed = 0

        for pos, idx in enumerate(english_indices):
            if not cleaned_texts[pos].strip():
                continue

            translation = self._cache.get(hashes[pos])

            if translation is not None:
                df_out.at[idx, "text"] = translation
                df_out.at[idx, "language"] = "de"
                df_out.at[idx, "is_translated"] = True
                df_out.at[idx, "translation_status"] = "success"
                n_success += 1
            else:
                df_out.at[idx, "translation_status"] = "failed"
                n_failed += 1

        logger.info(
            "Translation finished. Success: %s | Failed: %s | Empty/skipped: %s",
            f"{n_success:,}",
            f"{n_failed:,}",
            f"{n_empty:,}",
        )

        return df_out

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _validate_columns(df: pd.DataFrame) -> None:
        missing = _REQUIRED_COLUMNS - set(df.columns)
        if missing:
            raise ValueError(
                f"DataFrame is missing required columns: {sorted(missing)}. "
                f"Found: {list(df.columns)}"
            )

    def _translate_in_batches(self, texts: List[str]) -> List[Optional[str]]:
        """
        Translate texts in batches.

        Returns:
            A list aligned with the input order.
            Failed items are returned as None.
        """
        if not texts:
            return []

        results: List[Optional[str]] = []
        starts = range(0, len(texts), self.batch_size)

        for start in tqdm(starts, desc="Translating batches"):
            batch = texts[start : start + self.batch_size]

            try:
                results.extend(self._translate_batch(batch))
            except Exception as exc:  # noqa: BLE001
                logger.error(
                    "Batch %d-%d failed (%s). Retrying item by item.",
                    start,
                    start + len(batch) - 1,
                    exc,
                )

                for text in batch:
                    try:
                        translated = self._translate_batch([text])
                        results.append(translated[0])
                    except Exception as item_exc:  # noqa: BLE001
                        logger.error(
                            "Single-item translation failed (%s). Keeping original text.",
                            item_exc,
                        )
                        results.append(None)

        return results

    def _translate_batch(self, texts: List[str]) -> List[str]:
        import torch

        if not texts:
            return []

        inputs = self._tokenizer(
            texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=self.max_length,
        ).to(self.device)

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=self.generation_max_new_tokens,
                num_beams=4,
            )

        return self._tokenizer.batch_decode(output_ids, skip_special_tokens=True)

    def _load_model(self) -> None:
        if self._model is not None and self._tokenizer is not None:
            return

        from transformers import MarianMTModel, MarianTokenizer

        logger.info("Loading model '%s' onto %s", MODEL_NAME, self.device)
        self._tokenizer = MarianTokenizer.from_pretrained(MODEL_NAME)
        self._model = MarianMTModel.from_pretrained(MODEL_NAME).to(self.device)
        self._model.eval()

        # Prefer max_new_tokens for generation and silence repeated warnings
        if hasattr(self._model, "generation_config") and self._model.generation_config is not None:
            self._model.generation_config.max_length = None

        logger.info("Model ready.")

    def _load_cache(self) -> None:
        if not self.cache_path or not self.cache_path.exists():
            return

        try:
            cached = pd.read_parquet(self.cache_path)

            if not _CACHE_COLUMNS.issubset(cached.columns):
                raise ValueError(
                    f"Cache file must contain columns {sorted(_CACHE_COLUMNS)}, "
                    f"but found {list(cached.columns)}"
                )

            self._cache = dict(zip(cached["hash"], cached["translated"]))
            logger.info(
                "Loaded %s cached translations from %s",
                f"{len(self._cache):,}",
                self.cache_path,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Could not load cache from %s (%s). Starting with empty cache.",
                self.cache_path,
                exc,
            )
            self._cache = {}

    def _save_cache(self) -> None:
        if not self.cache_path:
            return

        try:
            self.cache_path.parent.mkdir(parents=True,  exist_ok=True)
            pd.DataFrame(
                {
                    "hash": list(self._cache.keys()),
                    "translated": list(self._cache.values()),
                }
            ).to_parquet(self.cache_path, index=False)
            logger.debug("Cache saved (%d entries).", len(self._cache))
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to save cache to %s: %s", self.cache_path, exc)

    @staticmethod
    def _default_device() -> str:
        try:
            import torch
            if torch.cuda.is_available():
                return "cuda"
            if torch.backends.mps.is_available():
                return "mps"
        except ImportError:
            pass
        return "cpu"


def _clean_text(text: str) -> str:
    """
    Lightweight pre-translation cleaning, safe for netiquette analysis.

    Applies only structural normalization - does NOT alter tone, punctuation,
    casing, emojis, or other semantic signals that matter for classification.

    Steps:
        1. Strip leading/trailing whitespace
        2. Remove HTML tags
        3. Replace URLs with the placeholder [URL]
        4. Collapse multiple whitespace characters into one
    """
    if not isinstance(text, str):
        return ""
    # Remove HTML tags (e.g. <br>, <p>, <a href="...">)
    text = re.sub(r"<[^>]+>", " ", text)
    # Replace URLs (http/https/www) with a neutral placeholder
    text = re.sub(r"https?://\S+|www\.\S+", "[URL]", text)
    # Collapse whitespace (tabs, multiple spaces) to a single space
    text = re.sub(r"[ \t]+", " ", text)

    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _md5(text: str) -> str:
    return hashlib.md5(text.encode("utf-8")).hexdigest()